before:
  hooks:
    - go mod tidy
    - go mod vendor
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - package_name: prometheus-port-exporter
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: "José Carlos García"
    homepage: https://josecarlos.me
    maintainer: "José Carlos <hola@josecarlos.me>"
    description: "prometheus-port-exporter is a tool for monitoring your services easily."
    license: "GPL-3.0"
    formats:
      - deb
      - rpm
      - apk
    dependencies: []
    contents: []

# furies:
#   - account: "JoseCarlosGarcia95"
#     secret_name: FURY_IO_TOKEN

release:
  prerelease: auto
