name: Test and generate releases

on:
  push:
    tags:
    - "*"
    branches:
    - "*"
  pull_request:
    branches:
    - "*"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-release:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Fetch all tags
      run: git fetch --force --tags
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.x
    - name: Install CGO_ENABLED dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y build-essential

    - name: Set git-tag
      run: echo "GIT_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4.4.0
      with:
        # either 'goreleaser' (default) or 'goreleaser-pro'
        distribution: goreleaser
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}